import type { NeutralMediator, WaveInfo } from '../types';

export const neutralMediators: NeutralMediator[] = [
  {
    id: 'geneva',
    name: 'GENEVA DIPLOMATIC ACCORD',
    zone: 'ZONE G-1 (EURO-NEUTRAL CORRIDOR)',
    bufferType: 'Demilitarized Air Corridor',
    ambassador: 'Ambassador Elena Vance',
    status: 'CEASEFIRE_PROPOSED',
    proposalText: 'Immediate 45-second cessation of hostilities to evacuate urban casualties, repair power grids, and restock interceptor magazines.',
    reparationAid: 25,
    restockSAMs: 12,
    restockICBMs: 2,
  },
  {
    id: 'nordic',
    name: 'NORDIC SHIELD UNION',
    zone: 'ZONE N-2 (ARCTIC RADAR BUFFER)',
    bufferType: 'Early Warning Electronic Neutral Zone',
    ambassador: 'Envoy Torvald Lindqvist',
    status: 'MEDIATING',
    proposalText: 'Deployment of shared neutral radar transponders to jam hostile terminal warhead guidance systems by 30%.',
    reparationAid: 20,
    restockSAMs: 10,
    restockICBMs: 1,
  },
  {
    id: 'asean',
    name: 'ASEAN MARITIME BUFFER',
    zone: 'ZONE A-3 (MALACCA STRAIT PASS)',
    bufferType: 'Naval Exclusion Sanctuary',
    ambassador: 'High Commissioner Siti Nurhaliza',
    status: 'MEDIATING',
    proposalText: 'Enforce naval quarantine around sovereign coastal waters, preventing submarine ballistic cruise launches.',
    reparationAid: 20,
    restockSAMs: 12,
    restockICBMs: 1,
  },
  {
    id: 'swiss',
    name: 'SWISS PEACE COALITION',
    zone: 'ZONE S-4 (ALPINE REFUGE)',
    bufferType: 'Subterranean Emergency Haven',
    ambassador: 'Chancellor Jean-Luc Meyer',
    status: 'BROKERING',
    proposalText: 'Supply of advanced nano-concrete structural reinforcement kits to instantly stabilize fractured skyscraper foundations.',
    reparationAid: 30,
    restockSAMs: 14,
    restockICBMs: 2,
  },
];

export const waveConfigs: WaveInfo[] = [
  {
    waveNumber: 1,
    name: 'PROBE STRIKE: STEALTH BOMBER SORTIE & CRUISE MISSILES',
    defcon: 4,
    munitionType: 'cruise',
    warheadCount: 4,
    speed: 52,
    hasStealthBomber: true,
    briefing: 'Superpower deploys low-observable H-20 stealth bomber penetrating under the radar horizon to release hypersonic cruise missiles.',
  },
  {
    waveNumber: 2,
    name: 'HYPERSONIC GLIDE VEHICLE ATTACK',
    defcon: 3,
    munitionType: 'hypersonic',
    warheadCount: 6,
    speed: 65,
    hasStealthBomber: false,
    briefing: 'Mach 8.5 glide vehicles skipping across upper atmosphere with plasma sheath. Blind enemy radar to counter!',
  },
  {
    waveNumber: 3,
    name: 'DRAGON-41 MIRV CLUSTER & DUAL STEALTH INTRUSION',
    defcon: 2,
    munitionType: 'mirv',
    warheadCount: 8,
    speed: 74,
    hasStealthBomber: true,
    briefing: 'Multi-vector assault combining sub-radar stealth sorties with heavy MIRV ballistic warhead clusters.',
  },
  {
    waveNumber: 4,
    name: 'SATURATION BALLISTIC ICBM ASSAULT',
    defcon: 2,
    munitionType: 'icbm',
    warheadCount: 10,
    speed: 84,
    hasStealthBomber: false,
    briefing: 'Simultaneous multi-vector nuclear warheads aimed at civilian grid and launch silos. Deploy decoys to overwhelm SAMs!',
  },
  {
    waveNumber: 5,
    name: 'DEFCON 1 ASYMMETRIC APOCALYPSE PROTOCOL',
    defcon: 1,
    munitionType: 'mirv',
    warheadCount: 14,
    speed: 98,
    hasStealthBomber: true,
    briefing: 'Unrestricted strategic retaliation. Intercept stealth fleet, blind early warning radar grids, and neutralize command bunkers!',
  },
];
